name: CI Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
        
      # Build
      - name: Build with Maven
        run: mvn package

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: RayTraceAntiXray Artifact
          path: |
            RayTraceAntiXray/target/
